### ISSUE TITLE
Raid Frame - Death & Offline Indicator not working

### ISSUE THREAD

**Issue by Spegeli** [Shadow-and-Light/shadow-and-light#10]
**Description**
In the Raid Frames the Death and Offline Indicator seems not working.

![Screen1](https://user-images.githubusercontent.com/19636318/131892222-964fe5c7-5df4-4adc-8b14-6ef294dc3f25.png)
![Screen2](https://user-images.githubusercontent.com/19636318/131892224-b9fa4314-abe3-40e6-b9f1-32073dea6188.png)

I changed nothing in the last time (in the settings) except updating ElvUi & S&L.

**Shadow & Light Version**
4.31

**ElvUI Version**
12.44

**Expected Behavior**
Icons should be showen on Raid Frame

**Actual Behavior**
No Icons showen on Raid Frame

**Comment by Repooc** [comment]
ur elvui is out of date, not sure if that is the issue but u def need to update before posting an error

**Comment by Repooc** [comment]
When you respond, make sure to do `/slerror on` then test and show a picture of your ui with `/estatus` window showing

**Comment by Spegeli** [comment]
sry typing wrong numbers, current elvui ist 12.44 ^^

![Screen3](https://user-images.githubusercontent.com/19636318/131894070-cf8ff120-88c7-416f-86a6-84778e1e127c.png)

**Comment by Repooc** [comment]
ok ill have to take a look later to debug it, prob not til over the weekend if i have some extra free time thanks for pointing it out and responding back so fast lol

**Comment by Spegeli** [comment]
Any news?

**Comment by Repooc** [comment]
yeah should be on the dev branch
sorry i forgot to respond as i been kind of busy irl and working on something i havent disclosed yet lol
If you use curse, u can set to use the alpha build, if you use ajour/wowup, u will need to make sure the source is curse and use the alpha version

**Comment by Spegeli** [comment]
Ok all working again...thx ;-)

**Comment by Spegeli** [comment]
Ok one last thing is broken:

![Screen](https://user-images.githubusercontent.com/19636318/133226858-f66ede84-5575-421b-8e0c-02b378b30973.png)

Anchor point is working, but X and Y Offsets not.
This happens on all Group / Raid Frames for Death & Offline Indicator.

**Comment by Repooc** [comment]
redownload and try that

**Comment by Spegeli** [comment]
> redownload and try that

Works perfect now, thx for your fast support ^^
