### ISSUE TITLE
AddOn 'ElvUI_SLE' tried to call the protected function 'ObjectiveTrackerFrame:Show()'.

### ISSUE THREAD

**Issue by gotex007** [Shadow-and-Light/shadow-and-light#104]
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_SLE' tried to call the protected function 'ObjectiveTrackerFrame:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Show'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerContainer.lua"]:101: in function <...ectiveTracker/Blizzard_ObjectiveTrackerContainer.lua:43>
[string "=(tail call)"]: ?
[string "@Blizzard_SharedXML/MixinUtil.lua"]:341: in function <Blizzard_SharedXML/MixinUtil.lua:340>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by Repooc** [comment]
https://github.com/tukui-org/ElvUI/wiki/errors

You also have not shared any information regarding version numbers and such... `/slerror on` and reproduce with how to reproduce the issue after doing the command in chat, and showing the `/estatus` window as well

**Comment by gotex007** [comment]
I literally enter combat and it throws the error. Taunt logging is disabled in elvui and there is no option for it in bugsack. As far as I can find, buggrabber doesn't have actual settings. I can't know if the addon throws an error or not without bugsack to catch it so /slerror doesn't help this process at all, but here's the [estatus window if you want version information](https://i.imgur.com/UEaSsFR.png).

So I don't know what to tell you or what more to do. It's not dismissable because bugsack gives audio when the error is triggered. As far as I know, you can just go enter combat with a dummy and it happens.

**Comment by Repooc** [comment]
Ok well you do NOT need bug sack and bug grabber to see errors, even taints. Bug sack will not hide taints, especially when you do `/slerror on` or even `/edebug on` which essentially does the same thing. One is from ElvUI which disables all addons but ElvUI, and the other disables all addons but ElvUI and S&L and both set scriptErrors cvar to enable and will show errors you come across.  Taint logs do not show the correct addon 99.9% of the time and just shows the last addon that access the tainted obj and doesnt mean that addon is the cause of the taint.  If you still feel lost or whatever it is without Bug Sack and Bug Grabber after doing `/slerror on`, go reenable just those 2 addons. Here is a quick clip of me at the dummies getting into combat with ElvUI, S&L, and Weakauras with some WA loaded. There are at least 1 known taint that ElvUI is causing in 13.71 and possibly be your issue. Both S&L and ElvUI have changes made in the dev builds of both that may help as well.
https://github.com/user-attachments/assets/bd98a01f-2183-4fa5-89c5-239acc04cd7d

**Comment by gotex007** [comment]
I think the ElvUI update did fix the error because it doesn't happen since the update.
