### ISSUE TITLE
click itme on wow quest tracker

### ISSUE THREAD

**Issue by grilor** [Shadow-and-Light/shadow-and-light#106]
**Description**
Message: ADDON_ACTION_FORBIDDEN: ElvUI_SLE tried to call the protected function 'UseQuestLogSpecialItem()'.
Time: Wed Jul 31 08:14:50 2024
Count: 4
Stack: ADDON_ACTION_FORBIDDEN: ElvUI_SLE tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals: self = Button {
 NormalTexture = Texture {
 }
 HotKey = FontString {
 }
 questLogIndex = 2
 count = 0
 charges = 0
 template = "QuestObjectiveItemButtonTemplate"
 rangeTimer = 0.102000
 Count = FontString {
 }
 used = true
 icon = Texture {
 }
 Cooldown = Cooldown {
 }
}
button = "LeftButton"

**Shadow & Light Version**
4.81

**ElvUI Version**

**Steps to Reproduce**
just try to click the time on the quest tracker 

**Expected Behavior**
for the time to work

**Actual Behavior**
I get a pop up form bug catcher

**Comment by Repooc** [comment]
Yeah looks like we may have to remove the auto hide option as the only way to make it work is if we hide the whole objective tracker and not just minimize it or sections of it. Disable the section in s&l config labaeled Quests

**Comment by grilor** [comment]
ok thanks you ill try that right after the servers come bak up

**Comment by Repooc** [comment]
worked around in dev build
