### ISSUE TITLE
Error with the UI button "A"

### ISSUE THREAD

**Issue by Johunn** [Shadow-and-Light/shadow-and-light#108]
**Description**
Hello, when I press the "A" button on the UI buttons menu I have an error message.

**Shadow & Light Version**
4.81

**ElvUI Version**
13.72

**Steps to Reproduce**
1. I press the A button
2. Error message

**Expected Behavior**
It should opens the addon manager

**Actual Behavior**
I have en error message 

**ElvUI + S&L Enabled**
Same thing

**Additional Information**

**Error Log**
Message: Interface/AddOns/ElvUI_SLE/modules/uibuttons.lua:31: attempt to index field 'GameMenuButtonAddons' (a nil value)
Time: Fri Aug  2 22:25:46 2024
Count: 1
Stack: Interface/AddOns/ElvUI_SLE/modules/uibuttons.lua:31: attempt to index field 'GameMenuButtonAddons' (a nil value)
[string "@Interface/AddOns/ElvUI_SLE/modules/uibuttons.lua"]:31: in function <Interface/AddOns/ElvUI_SLE/modules/uibuttons.lua:31>
[string "@Interface/AddOns/ElvUI_SLE/Libraries/Core/LibElv-UIButtons-1.0/LibElv-UIButtons-1.0.lua"]:142: in function <...s/Core/LibElv-UIButtons-1.0/LibElv-UIButtons-1.0.lua:141>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'GameMenuButtonAddons' (a nil value)"
_G = <table> {
 ERR_OUT_OF_CHI = "Pas assez de chi"
 DH_HAVOC_CORE_ABILITY_2 = "Attaque puissante en mêlée qui consomme de la fureur. Si elle inflige un coup critique, une partie de la fureur est récupérée."
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Colorer les noms des unités."
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 783
 SPELL_FAILED_CUSTOM_ERROR_71 = "Ce bambocheur aimerait danser avec vous."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 421
 ClassTrialTimerDisplayMixin = <table> {
 }
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 375
 MerchantItem7AltCurrencyFrameItem1Text = MerchantItem7AltCurrencyFrameItem1Text {
 }
 OPTION_SHOW_ACTION_BAR5_TOOLTIP = "Ancré sur le côté gauche de la barre d’actions 4 par défaut"
 BINDING_NAME_NAMEPLATES = "Barres d’info des adversaires"
 CHAT_HEADER_SUFFIX = " : "
 COVENANT_MISSIONS_HEALTH = "Santé"
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "Salle de Main-Noire"
 WorldQuestTrackerWorldMapPOIWorldQuestTrackerWorldSummarySquarePOI2BorderShineAnimation3 = WorldQuestTrackerWorldMapPOIWorldQuestTrackerWorldSummarySquarePOI2BorderShineAnimation3 {
 }
 AceConfigDialogTooltipTexture20 = AceConfigDialogTooltipTexture20 {
 }
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 36
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Peur"
 Boss1TargetFrameValue = Boss1TargetFrameValue {
 }
 ElvUI_Bar6Button6 = ElvUI_Bar6Button6 {
 }
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 RaidUtility_CloseButton = RaidUtility_CloseButton {
 }
 LE_GAME_ERR_AZERITE_ESSENCE_SELECTION_FAILED_ESSENCE_NOT_UNLOCKED = 1074
 DUNGEON_FLOOR_DRAGONBLIGHTCHROMIESCENARIO2 = "Andorhal"
 ElvUIReagentBankFrameItem23SearchOverlay = ElvUIReagentBankFrameItem23SearchOverlay {
 }
 WowTokenRedemptionFrameBg = WowTokenRedemptionFrameBg {
 }
 DetailsBreakdownWindowTabFrameSummary8337SpellScrollContainerSpellScrollSpellBarButton41FontString12 = DetailsBreakdownWindowTabFrameSummary8337SpellScrollContainerSpellScrollSpellBarButton41FontString12 {
 }
 SPELL_FAILED_CUSTOM_ERROR_152 = "Vous devez choisir une spécialisation pour pouvoir utiliser Ascendance."
 LAG_TOLERANCE = "Tolérance de latence"
 RCLootCouncil_Tooltip_ParseTextLeft1 = RCLootCouncil_Tooltip_ParseTextLeft1 {
 }
 STABLE_PET_ABILITIES_LIST_HEADER = "Techniques spéciales"
 ElvUI_Bar5Button9NormalTexture = ElvUI_Bar5Button9NormalTexture {
 }
 TUTORIAL61_SPELLID_DRUID = "768"
 CONQUEST_BAR = "Conquête : %d/%d"
 MultiBarLeftButton9Border = MultiBarLeftButton9Border {
 }
 LE_GAME_ERR_NOT_ON_TOURNAMENT_REALM = 888
 UIWidgetCenterDisplayFrameText = UIWidgetCenterDisplayFrameText {
 }
 BtWLoadoutsFrameLoadoutsButtonDisabledTexture = BtWLoadoutsFrameLoadoutsButtonDisabledTexture {
 }
 OPTION_TOOLTIP_SHOW_ACCOUNT_ACHIEVEMENTS = "Activer cette option n’affichera que les hauts faits de votre personnage quand d’autres joueurs l’inspecteront, ou qu’ils utiliseront le site Internet Blizzard ou l’application mobile."
 j = 7
 UNCHECKED_ENABLED = 2
 OPTION_TOOLTIP_FIX_LAG = "Activer cette option réduit les ralentissements de l'interface utilisateur, mais risque de diminuer grandement le taux de rafraîchissement."
 ARTIFACT_XP_FULL = "%s est au niveau maximum."
 VOICEMACRO_8_Tr_1_FEMALE = 

```

**Comment by Repooc** [comment]
Fixed in the next version
