### ISSUE TITLE
font replacement not working on objective tracker

### ISSUE THREAD

**Issue by jardragon901** [Shadow-and-Light/shadow-and-light#113]
**Description**
When replacing fonts on the objective tracker, the option to change the font for the tracker entries does not work.

**Shadow & Light Version**
4.81

**ElvUI Version**
13.74

**Expected Behavior**
![Screenshot 2024-08-15 151021](https://github.com/user-attachments/assets/d250bbea-f48e-4ad2-a246-6949008a81d1)
font should swap to the font i choose in the dropdown

**Actual Behavior**
![Screenshot 2024-08-15 151106](https://github.com/user-attachments/assets/7f584c45-f839-4741-83fb-8f4ccd562254)

font isn't
 switching to the font i choose

**Error Log**
Not seeing any errors generated
```

```

**Comment by Repooc** [comment]
already have something in the works

**Comment by Repooc** [comment]
can change font in the dev build currently
