### ISSUE TITLE
Outdated Fishing Libraries for SLE?

### ISSUE THREAD

**Issue by Yerfdoggy** [Shadow-and-Light/shadow-and-light#118]
**Description**
I’ve been experiencing an issue with Fishing Buddy (version 1.24.1) where the addon wouldn't load properly, leading to errors. I’m using Elvui with the Shadow and Light Plugin and also have Bugsack installed to capture any bugs.

After encountering the initial loading error, I found a suggested fix in the comments of the Fishing Buddy CurseForge Comments section (here - https://www.curseforge.com/wow/addons/fishingbuddy/comments), which involved updating the fishing libraries. I followed the instructions, but now I’m encountering a new error that says, "Fishing Buddy: Did not Initialize correctly." when trying to access the fishing buddy menu. I've also included the errors I receive when I initially load into the WoW.

I noticed that the dev mentioned this could be related to an outdated SLE Fishing Library, and they suggested copying over the LibFishing-1.0 library to the Core SLE libraries folder.

Here’s what I’ve done so far:

_Updated Fishing Buddy with the provided library fix.
Copied LibFishing-1.0 to the SLE Core/Libs folder._

I'm posting this here as the dev from the Fishing Buddy forum suggested that you may want to look at this.

**Shadow & Light Version**
4.81

**ElvUI Version**
13.76

**Steps to Reproduce**

1. Have Elvui addon, Shadow and Light plugin, Fishing Buddy addon loaded with latest libraries
2. On loading into WoW, you should get the error that I have posted further down in this post.
3. If you type /fb you should get "Fishing Buddy: Did not Initialize correctly."

**Expected Behavior**
Loads the Fishing Buddy Menu

**Actual Behavior**
Fishing Buddy: Did not Initialize correctly.

**Error Log**
7x ...SLE/Libraries/Core/LibFishing-1.0-101109/LibFishing-1.0.lua:200: attempt to call global 'GetSpellLink' (a nil value)
[string "@ElvUI_SLE/Libraries/Core/LibFishing-1.0-101109/LibFishing-1.0.lua"]:200: in function `GetFishingSpellInfo'
[string "@FishingBuddy/FishingBuddy.lua"]:1783: in function <FishingBuddy/FishingBuddy.lua:1697>

Locals:
self = <table> {
 SCHOOLS = <table> {
 }
 ITEM_TYPE = 6
 FishingLevels = <table> {
 }
 ITEM_ICON = 10
 CastButton = <table> {
 }
 COLOR_HEX_GOLD = "ffd700"
 registered = <table> {
 }
 CastingKeys = <table> {
 }
 SCHOOL_FISH = 0
 ZANDALAR = 10
 KALIMDOR = 1
 LURE_NAME = "Fishing Lure"
 COMPRESSED_OCEAN = 9
 SCHOOL_FIRE = 8
 SCHOOL_FLOTSAM = 7
 SCHOOL_OIL = 5
 SCHOOL_TASTY = 4
 SCHOOL_WATER = 3
 SCHOOL_DEBRIS = 2
 ITEM_LINK = 2
 EASTERN_KINDOMS = 2
 SCHOOL_WRECKAGE = 1
 caughtSoFar = 0
 COLOR_HEX_GREEN = "00ff00"
 MOUSE3 = "Button5Down"
 ITEM_EQUIPLOC = 9
 UNKNOWN = "UNKNOWN"
 ITEM_SUBTYPE = 7
 COLOR_HEX_BLACK = "000000"
 COLOR_HEX_CYAN = "00ffff"
 COLOR_HEX_BLUE = "0000ff"
 COLOR_HEX_PURPLE = "9980CC"
 COLOR_HEX_COPPER = "eda55f"
 COLOR_HEX_SILVER = "c7c7cf"
 COLOR_HEX_WHITE = "ffffff"
 ITEM_LEVEL = 4
 COLOR_HEX_YELLOW = "ffff00"
 COLOR_HEX_RED = "ff0000"
 COLOR_HEX_ORANGE = "ff7f00"
 HBD = <table> {
 }
 MapButton = <table> {
 }
 continent_fishing = <table> {
 }
 PANDARIA = 6
 MOUSE2 = "Button4Down"
 MOUSE1 = "RightButtonDown"
 SHADOWLANDS = 11
 SCHOOL_CHURNING = 6
 havedata = false
 PLAYER_SKILL_READY = "PlayerSkillReady"
 ITEM_STACK = 8
 gearcheck = true
 NORTHREND = 4
 MOUSE4 = "MiddleButtonDown"
 ITEM_MINLEVEL = 5
 hasgear = false
 BROKEN_ISLES = 8
 DRAENOR = 7
 DRAGONFLIGHT = 12
 THE_MAELSTROM = 5
 OUTLAND = 3
 SCHOOL = "school"
 ITEM_NAME = 1
 KUL_TIRAS = 9
 ITEM_QUALITY = 3
}
fishing = 8
name = "Fishing"
_ = 4620674
_ = 76
_ = 300
count = 2
offset = 213
_ = 356
id = nil
(for index) = 1
(for limit) = 2
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 214
(*temporary) = "spell"
(*temporary) = "attempt to call global 'GetSpellLink' (a nil value)"

**Comment by Repooc** [comment]
idk what u are trying to do but i never looked at that addon and have dont some fixes for the fishing library including that SpellLink error, if you grab the latest dev/alpha build from gh or a client like wowup, u can see there has been updates here... i have not gone out and looked for an update to the lib myself just did fixes for deprecated api calls like the one u got the error for above

**Comment by Yerfdoggy** [comment]
@Repooc Thank you for responding promptly.  In short, I'm trying to use the fishing buddy addon with the SLE Elvui Plugin, but it was giving me errors. I posted on the Fishing Buddy curseforge comments forum and they resolved it by advising me to update the SLE Fishing library to the one that they had. and then they suggested to post here as it seems to be a SLE bug with the fishing library that SLE uses. My issue is resolved however, thought I would update you folks.  

Also, I believe I have the latest version of SLE and I use WoWup-CF to regularly update my apps.  please close if working as intended..

**Comment by Repooc** [comment]
Using the app doesnt mean u get the alpha/dev build automatically and glad u dont.  You should only use it if suggested which is done until 4.82 is out then switch back to release build.

I will take a look and if i have to i can just adjust the lib to a be modified one so they wont conflict with the other addon

**Comment by Repooc** [comment]
Actually we already changed it so that our lib version will not effect other people.. You just need to update to the alpha build with wow up (right click it in the addon list in the client)

**Comment by Yerfdoggy** [comment]
> Actually we already changed it so that our lib version will not effect other people.. You just need to update to the alpha build with wow up (right click it in the addon list in the client)
