### ISSUE TITLE
"Dedicated Vehicle Bar" keybind for the last button (button 7) is wrong

### ISSUE THREAD

**Issue by evaluc** [Shadow-and-Light/shadow-and-light#120]
**Description**

Similar/same as this previous issue: https://github.com/Shadow-and-Light/shadow-and-light/issues/80

Different version of ElvUI + S&L though, and the expansion is The War Within vs. Dragonflight, after many API changes in 11.0.

The dedicated vehicle bar populates the 7th button with ElvUI_Bar1Button12 (and the corresponding keybind).

**Shadow & Light Version**

4.84

**ElvUI Version**

13.76

**Steps to Reproduce**

1. Enable S&L Dedicated Vehicle Bar
2. Mount on a skyriding-enabled mount
3. The 7th button slot on the vehicle bar will contain the 12th button from ElvUI_Bar1

**Expected Behavior**

The 7th button on the dedicated vehicle bar should be ElvUI_Bar1Button7 and the corresponding keybind.

**Actual Behavior**

The dedicated vehicle bar populates the 7th button with ElvUI_Bar1Button12 and the corresponding keybind.

**ElvUI + S&L Enabled**

Yes, the issues happens with only ElvUI + S&L enabled.

**Only ElvUI Enabled**

N/A - dedicated vehicle bar is a feature of Shadow & Light.

**Additional Information**

Primarily this is when skyriding, so it's possible the issue doesn't occur in a "real" vehicle.

Putting the intended ability (Second Wind) in the appropriate slot on ElvUI_Bar1lets me use the ability, but it doesn't appear on the dedicated vehicle bar unless it's put in the 12th button slot with a mod-shift keybind that's inconvenient.

My keybinds are set such that I want to use the 7th action bar button for vehicle/skyriding controls and have it actually appear on the dedicated vehicle bar.

**Error Log**

N/A
```

```

**Comment by Repooc** [comment]
actually this is intended as there is no need to for the rest of the buttons that we have seen as blizzard tends to put the exit vehicle button on 12, which is why it is like that
