### ISSUE TITLE
[Feature Request] <Russian language translation>

### ISSUE THREAD

**Issue by Hollicsh** [Shadow-and-Light/shadow-and-light#14]
Hello guys !
I found several typos in the Russian localization and translated them properly.
I ask the development team to update the translation file.

[ElvUI_SLE.zip](https://github.com/Shadow-and-Light/shadow-and-light/files/7270210/ElvUI_SLE.zip)

**Comment by Repooc** [comment]
tbh, u should do a pull request for stuff like this.  @DarthPredator speaks russian so i would yield to him on what u feel is wrong vs not

**Comment by Hollicsh** [comment]
Good.
What do I need to do ?

**Comment by DarthPredator** [comment]
Accepted
