### ISSUE TITLE
Left chat pane is bugged

### ISSUE THREAD

**Issue by Dahhhaka** [Shadow-and-Light/shadow-and-light#2]
**Description**
Ever since the update on 07-05, the left chat pane is completely non functional

Nothing shows up in the chat pane from any text channel. If you try to type something yourself, the text appears underneath the bar at the bottom of the screen.

**Shadow & Light Version**
v4.23

**ElvUI Version**
12.33

**Steps to Reproduce**
Try to type anything or look at chat

**Comment by Angakkorsuaq** [comment]
This is how my chat looks with S&L enabled.

![S L chat bug](https://user-images.githubusercontent.com/78351430/124600836-ed489a00-de45-11eb-8730-220ea3b83b32.png)

Also running Latest updates. Tried earlier versions and doesnt seems to fix the problem.
Shadow & Light Version
v4.23

ElvUI Version
12.33

**Comment by Repooc** [comment]
Invalid, dont use the alpha version, read the chat message above....
