### ISSUE TITLE
[Feature Request] Ability to hide chat panels in pet battle

### ISSUE THREAD

**Issue by leemitchell25** [Shadow-and-Light/shadow-and-light#24]
Hi there,

Recently changed my ElvUI and the chat panel placement now interferes with the Pet Battle UI. Noticed that Shadow & Light can hide the panels in combat so I figured out a way to have it also hide them in pet battles. I think it would be great if this was implemented in future versions of Shadow & Light for other users.

The modifications I made are as follows.

--- --- ---

In defaults\profile.lua add the following code under line 294:

```
["petbattlehide"] = "NONE",
```

In modules\chat\chat.lua in function C:Initialize add the following after the --Combat Hide code:

```
--PetBattle Hide
self:RegisterEvent('PET_BATTLE_OPENING_START', 'PetBattle')
self:RegisterEvent('PET_BATTLE_CLOSE', 'PetBattle')
```

--- --- ---

In modules\chat\chat.lua add the following function after the C:Combat(event) function:

```
function C:PetBattle(event)
	if event == 'PET_BATTLE_OPENING_START' then
		if E.db.sle.chat.petbattlehide == 'BOTH' or E.db.sle.chat.petbattlehide == 'RIGHT' then
			RightChatPanel:Hide()
			RightChatToggleButton:Hide()
		end
		if E.db.sle.chat.petbattlehide == 'BOTH' or E.db.sle.chat.petbattlehide == 'LEFT' then
			LeftChatPanel:Hide()
			LeftChatToggleButton:Hide()
		end
	elseif event == 'PET_BATTLE_CLOSE' then
		if not RightChatPanel:IsShown() then
			RightChatPanel:Show()
			RightChatToggleButton:Show()
		end
		if not LeftChatPanel:IsShown() then
			LeftChatPanel:Show()
			LeftChatToggleButton:Show()
		end
	end
end
```

--- --- ---

In option\chat\chat_c.lua in function configTable() add the following code after the combathide options:

```
petbattlehide = {
	order = 10, type = "select",
	name = L["Hide In Pet Battle"],
	get = function(info) return E.db.sle.chat.petbattlehide end,
	set = function(info, value)	E.db.sle.chat.petbattlehide = value end,
	values = {
		["NONE"] = NONE,
		["BOTH"] = L["Both"],
		["LEFT"] = L["Left"],
		["RIGHT"] = L["Right"],
	}
},
```

--- --- ---

And finally, in option\chat\chat_c.lua in function configTable() change the order for the setupDelay options from 10 to 11.

--- --- ---

Thank you for all your hard work on Shadow & Light. It's an awesome addition to ElvUI. :)

**Comment by brett1337** [comment]
Also the RMBA interface next to the minimap stays open in a pet battle when it shouldn't

**Comment by Repooc** [comment]
> Also the RMBA interface next to the minimap stays open in a pet battle when it shouldn't

The what? I don't pet battle other than to test something specific to it.

**Comment by brett1337** [comment]
Ah, sorry I guess it's not always the same letters. There are 4 letter buttons that I'm not sure what all of them do, but they persist during pet battles, when all UI elements are supposed to hide. Here it is CASR, and the number is the addons list button.

![image](https://github.com/user-attachments/assets/95d62b03-a701-4a0b-9292-d5d9dc424bba)

**Comment by Repooc** [comment]
ahh ui buttons

**Comment by Repooc** [comment]
> Ah, sorry I guess it's not always the same letters. There are 4 letter buttons that I'm not sure what all of them do, but they persist during pet battles, when all UI elements are supposed to hide. Here it is CASR, and the number is the addons list button.
> 
> ![image](https://private-user-images.githubusercontent.com/12449286/363795729-95d62b03-a701-4a0b-9292-d5d9dc424bba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NzcxOTQsIm5iZiI6MTcyNTU3Njg5NCwicGF0aCI6Ii8xMjQ0OTI4Ni8zNjM3OTU3MjktOTVkNjJiMDMtYTcwMS00YTBiLTkyOTItZDVkOWRjNDI0YmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDIyNTQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkOTM0YjYyNjE4NTFkMmNhMTA2NWI5NmUyNzkwM2MzNTkzNDQzNGUxOWM2OTY0NmZhMjFiM2VmYzMwNmU3ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IIsWOKT5GI8yvtvfPzDCP3_O1rIBb4xNRO-qE1G4DSQ)

u can use the visibility section to hide them during petbattle, put `[petbattle] hide; show`

**Comment by brett1337** [comment]
cool, done. by the way i never knew what the ui buttons did until i just went into the menu right now, i think it would be cool to put tooltips on each UI button (im going to use the addons one all the time now) but its just a passing thought, thanks for the help!
