### ISSUE TITLE
Cannot clear non-existent WoW Token in Darth panel currency

### ISSUE THREAD

**Issue by waddlingeagle** [Shadow-and-Light/shadow-and-light#29]
**Description**

Darth panel lists currency, but it shows a WoW Token that I do not have with no way to clear it from the list.
**Shadow & Light Version**

4.33
**ElvUI Version**

12.58
**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. Step 4

Click on currency on Darth Panel. Shows list of all currencies. Shows a non-existent WoW token under "miscellaneous."
**Expected Behavior**

WoW Token should not be there
**Actual Behavior**

**ElvUI + S&L Enabled**

**Only ElvUI Enabled**

**Additional Information**

**Error Log**

```

```

**Comment by Repooc** [comment]
Without pictures, how to say what you are referring to.  S&L no longer has its own currency thing as ours is just a combination of ElvUI Gold and Currency Datatext which is all elvui code.

**Comment by waddlingeagle** [comment]
Thanks for the quick response. Does this help? The WoW Token appears under “Miscellaneous."

**Comment by Repooc** [comment]
no picture = no help

**Comment by Repooc** [comment]
to be honest, this is prob best in discord as i am not going to keep going back and forth via a ticket as this doesnt appear to be an issue but at the same time, i am not going to purchase a wow token to test either atm esp when its not even s&l code

**Comment by waddlingeagle** [comment]
You did not get the picture I sent?

**Comment by Repooc** [comment]
![image](https://user-images.githubusercontent.com/1479745/147856996-414b7acf-309b-42b9-8a26-da66780cdcf5.png)
u can see in this ticket i do not see a picture

**Comment by Repooc** [comment]
![image](https://user-images.githubusercontent.com/1479745/147857022-118e1997-70bc-494a-8958-98ff1c9085a8.png)
i am not sure if you mean this? as this list current wow token price

**Comment by waddlingeagle** [comment]
Probably right. Thanks

**Comment by waddlingeagle** [comment]
Okay, thanks. That is what it was. So it is not saying that I have a token, but is only listing the current price. Thanks so much. Have a great new year.

**Comment by Repooc** [comment]
you as well
