### ISSUE TITLE
Kindly dont break things that already work, Chat Not Working, Map Not Working ?!?

### ISSUE THREAD

**Issue by ze3rax** [Shadow-and-Light/shadow-and-light#3]
Message: Interface\AddOns\ElvUI_SLE\modules\chat\chat.lua:55: attempt to index field 'chat' (a nil value)
Time: Fri Jul  9 12:42:24 2021
Count: 7
Stack: Interface\AddOns\ElvUI_SLE\modules\chat\chat.lua:55: attempt to index field 'chat' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_SLE\modules\chat\chat.lua"]:55: in function `func'
[string "@Interface\AddOns\ElvUI\Modules\Chat\Chat.lua"]:1471: in function `GetPluginIcon'
[string "@Interface\AddOns\ElvUI\Modules\Chat\Chat.lua"]:1949: in function `ChatFrame_MessageEventHandler'
[string "@Interface\AddOns\ElvUI\Modules\Chat\Chat.lua"]:2061: in function <Interface\AddOns\ElvUI\Modules\Chat\Chat.lua:2057>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ElvUI\Modules\Chat\Chat.lua"]:2065: in function `FloatingChatFrame_OnEvent'
[string "@Interface\AddOns\ElvUI\Modules\Chat\Chat.lua"]:2070: in function <Interface\AddOns\ElvUI\Modules\Chat\Chat.lua:2069>

Locals: errMsg = "Interface\AddOns\ElvUI_SLE\modules\chat\chat.lua:55: attempt to index field 'chat' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}
Message: Interface\AddOns\ElvUI_SLE\modules\chat\chat.lua:55: attempt to index field 'chat' (a nil value)
Time: Fri Jul  9 12:42:24 2021
Count: 7
Stack: Interface\AddOns\ElvUI_SLE\modules\chat\chat.lua:55: attempt to index field 'chat' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_SLE\modules\chat\chat.lua"]:55: in function `func'
[string "@Interface\AddOns\ElvUI\Modules\Chat\Chat.lua"]:1471: in function `GetPluginIcon'
[string "@Interface\AddOns\ElvUI\Modules\Chat\Chat.lua"]:1949: in function `ChatFrame_MessageEventHandler'
[string "@Interface\AddOns\ElvUI\Modules\Chat\Chat.lua"]:2061: in function <Interface\AddOns\ElvUI\Modules\Chat\Chat.lua:2057>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ElvUI\Modules\Chat\Chat.lua"]:2065: in function `FloatingChatFrame_OnEvent'
[string "@Interface\AddOns\ElvUI\Modules\Chat\Chat.lua"]:2070: in function <Interface\AddOns\ElvUI\Modules\Chat\Chat.lua:2069>

Locals: errMsg = "Interface\AddOns\ElvUI_SLE\modules\chat\chat.lua:55: attempt to index field 'chat' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by Repooc** [comment]
Kindly use and fill out the bug report template and maybe follow troubleshooting instructions and check for updates
