### ISSUE TITLE
Error with "Resurrect" and/or "Summon" window when moved.

### ISSUE THREAD

**Issue by MendoGH** [Shadow-and-Light/shadow-and-light#37]
Hi i get an error if i activate the option "Move Blizzard frames" and "Remember" usually with the "resurect now" and/or the "accept summon" window.
What happends is, when the windows shows up, if i move it and make it go (either by going away from my corpse or by clic on the button), the next time the window is supposed to show (when i die again later or go closer to my corpse just after or even get a summon) then the window doesnt show and i get a pretty long error message ( starting by : "Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: StaticPopup1:SetPoint" etc ...)

If i move the window and reload BEFORE make it show again then evrything ok. 

I can send the full error message if needed.

**Comment by Repooc** [comment]
next time the window is up, can u do `/fstack` and mouse over the window u are referring to (if 2 windows, do it for both and post the pictures here)  and also just for testing, try `/slerror on` and reproduce the issue, this will disable all addons but elvui, elvui options, and s&l
