### ISSUE TITLE
Shadow & Light funktioniert nach Installation nicht!

### ISSUE THREAD

**Issue by Muckwimp** [Shadow-and-Light/shadow-and-light#38]
**Description**

Shadow & Light funktioniert nach Installation nicht!

**Shadow & Light Version**

ElvUI_SLE-4.36

**ElvUI Version**

ElvUI-12.75

**Steps to Reproduce**

1. Step 1: Ich benutze ElvUI und Shadow & Light schon immer und ich wollte das PlugIn ElvUI Windtools installieren. Die Installation hat funktioniert und ElvUI Windtools war in ElvUI eingetragen. Doch es funktionierte nicht, weil ich es nicht aufrufen und einstellen konnte. Dabei stellte ich fest, dass Shadow & Light nicht in ElvUI angezeigt wurde, obwohl es installiert war. Im \Interface\AddOn-Verzeichis war es auch vorhanden und im WTF-Ordner unter Savevariables war auch die SL-lua-Datei vorhanden
2. Step 2: Ich habe dann Shadow & Light deinstalliert und die lua-Datei gelöscht und SL neu installiert! Egal ob ich es über Curse installiert habe oder die Datei heruntergeladen habe und dann in den AddOn-Ordner kopiert habe, ich konnte SL nicht aktivieren. Es war nicht unter ElvUI eingetragen, aber im AddOn-Verzeichnis vorhanden und auch beim Curse-Forge-AddOn-Manager wurde es angezeigt.
3. Step 3: Auch beim wiederholten Neustart oder Reload startete SL nicht mit der Installations-Routine.
4. Step 4: Dieses Problem habe ich aber nur bei meinem Magier-Charakter, den ich zurzeit nur spiele. Alle anderen Charakter (11 Stück) haben das Problem nicht.
Ich habe bei meinem Magier ein anderes Profil importiert, was alles auch funktioniert hat, ebenso bei meinen anderen Chars. Nur bei Magier funktioniert SL nicht mehr. Warum auch immer?

**Expected Behavior**

Ich habe erwartet, dass ich Shadow & Light neu installieren und nutzen kann, um dann ElvUI Windtools zu benutzen, welch ja wohl ohne SL nicht funktioniert.
Das Problem ist erst seit ein paar Tagen aufgetreten, wo es eine neue Version ElvUI-12.75 und ElvUI_SLE-4.36 gab. Updates werden von mir immer regelmäßig durchgeführt.

**Actual Behavior**

Shadow & Light startet nicht. ElvUI Windtools kann nicht benutzt werden

**ElvUI + S&L Enabled**

Bitte geben Sie an, ob Sie es reproduzieren können oder nicht
ElvUI ist aktiviert und funktioniert, S&L kann nicht aktiviert werden.

Das wie oben genannt.

Dieser Befehl funktioniert bei mir nicht. Im Chat erscheint Hilfe?

**Only ElvUI Enabled**

Der Befehl /estatus funktioniert.

Der Befehl /estatus funktioniert

Habe ich nicht ausprobiert.

**Additional Information**

Ich habe eigentlich in meiner 18jährigen Spieltätigkeit von World of Warcraft noch nie irgendwelche Probleme gehabt. Was jetzt passiert ist, ist auch nicht logisch. Die AddOns sind installiert, werden in den Verzeichnissen angezeigt; nur nicht in ElvUI und S&L lässt sich nicht starten.

**Error Log**

Keine Fehler angezeigt bekommen.

```
Keine Fehler angezeigt bekommen.

```

**Comment by Repooc** [comment]
It is prob a conflict with another addon... You will need to do `/edebug on` which will disable everything but ElvUI and ElvUI_OptionsUI, then go in and enable Shadow & Light only and test.

**Comment by Muckwimp** [comment]
Vielen Dank für die schnelle Hilfe. Funktioniert wieder.

**Comment by Repooc** [comment]
That's because you have an addon that is breaking something.

**Comment by Repooc** [comment]
S&L should load with no issues with masque enabled

**Comment by Merathilis** [comment]
> Es hat an "Masque" gelegen. Alles okay. Danke !!!

Also Masque ist eher unwahrscheinlich jetzt. 🤔
