### ISSUE TITLE
Error on Raid Finder menu

### ISSUE THREAD

**Issue by Naxterra** [Shadow-and-Light/shadow-and-light#42]
**Description**
When I select Raid Finder UI gives error. Also, cannot select anything from dropdown menu.

**Shadow & Light Version**
4.40

**ElvUI Version**
12.81

**Steps to Reproduce**
Press I
Select Raid Finder
Errors occur.
Try to select anything from dropdown menu.
Nothing can be selected, only errors.

**Expected Behavior**
Raid Finder should not give any errors

**Actual Behavior**
Message: Interface\FrameXML\RaidFinder.lua:294: attempt to concatenate a nil value
Time: Wed Aug  3 02:24:37 2022
Count: 1
Stack: Interface\FrameXML\RaidFinder.lua:294: attempt to concatenate a nil value
[string "=[C]"]: ?
[string "@Interface\FrameXML\RaidFinder.lua"]:294: in function `initFunction'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:78: in function `UIDropDownMenu_Initialize'
[string "@Interface\FrameXML\RaidFinder.lua"]:176: in function <Interface\FrameXML\RaidFinder.lua:174>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\PVEFrame.lua"]:315: in function `GroupFinderFrame_ShowGroupFrame'
[string "@Interface\FrameXML\PVEFrame.lua"]:335: in function <Interface\FrameXML\PVEFrame.lua:333>

Locals: 

**ElvUI + S&L Enabled**

**Only ElvUI Enabled**

**Additional Information**

**Error Log**
Message: Interface\FrameXML\RaidFinder.lua:294: attempt to concatenate a nil value
Time: Wed Aug  3 02:24:37 2022
Count: 1
Stack: Interface\FrameXML\RaidFinder.lua:294: attempt to concatenate a nil value
[string "=[C]"]: ?
[string "@Interface\FrameXML\RaidFinder.lua"]:294: in function `initFunction'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:78: in function `UIDropDownMenu_Initialize'
[string "@Interface\FrameXML\RaidFinder.lua"]:176: in function <Interface\FrameXML\RaidFinder.lua:174>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\PVEFrame.lua"]:315: in function `GroupFinderFrame_ShowGroupFrame'
[string "@Interface\FrameXML\PVEFrame.lua"]:335: in function <Interface\FrameXML\PVEFrame.lua:333>

Locals: 
```


Message: Interface\FrameXML\RaidFinder.lua:294: attempt to concatenate a nil value
Time: Wed Aug  3 02:25:22 2022
Count: 14
Stack: Interface\FrameXML\RaidFinder.lua:294: attempt to concatenate a nil value
[string "=[C]"]: ?
[string "@Interface\FrameXML\RaidFinder.lua"]:294: in function `initFunction'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:78: in function `UIDropDownMenu_Initialize'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:1075: in function <Interface\SharedXML\UIDropDownMenu.lua:933>
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@Interface\SharedXML\UIDropDownMenuTemplates.lua"]:19: in function <Interface\SharedXML\UIDropDownMenuTemplates.lua:17>

Locals:

**Comment by Repooc** [comment]
That's not from Shadow & Light
![Screenshot_28.png](https://user-images.githubusercontent.com/1479745/182499576-9dd2e58e-0223-4263-8eed-40a427d7c31b.png)
