### ISSUE TITLE
Inspect Armory Transmog Arrow shows wrong items

### ISSUE THREAD

**Issue by Beet4** [Shadow-and-Light/shadow-and-light#43]
**Description**
I have Inspect Armory activated with enable arrows from transmog Items. Whenever I inspect someone and check their transmog with the transmog arrow it shows the wrong item. From what i can tell the items seems shifted around to different (wrong) slots.

**Shadow & Light Version**
4.40

**ElvUI Version**
12.83

**Steps to Reproduce**

1. Enable Inspect Armory in S&L
2. Enable Transmog Arrow
3. Inspect someone with a transmog on
4. Hover over Transmog Arrows for different slots, transmogs are not accurate to the slots

**Expected Behavior**
Show the correct transmog on the correct slot

**Actual Behavior**
Shows the wrong transmog on the wrong slots

**ElvUI + S&L Enabled**

Same behavior with /slerror on

**Only ElvUI Enabled**

Not feasible to test as it's an S&L feature

**Additional Information**

Screenshot below:
![image](https://user-images.githubusercontent.com/38279393/185765288-8250c536-173c-49ef-92fc-fccb1c2eb34a.png)
This screenshot shows a weapon transmogged on hands slot.

**Error Log**

```
No error
```

**Comment by Repooc** [comment]
confirmed. dont have time at this time to try to figure that out but will try to set some time for it when i can

**Comment by Repooc** [comment]
i just pushed what should fix that... i noticed that the arrows dont seem to come in on first inspect a lot of the time... separate issue i may have to look into later
