### ISSUE TITLE
WoW 10.0 - Dedicated Vehicle Bar

### ISSUE THREAD

**Issue by Evolutious** [Shadow-and-Light/shadow-and-light#44]
**Description**
The Dedicated Vehicle Bar is not displaying the actions.

**Shadow & Light Version**
4.45

**ElvUI Version**
12.95

**Steps to Reproduce**
1. Find a quest that puts you inside a vehicle that has usable actions
2. Notice how the default action bars hide and the dedicated vehicle bar show
3. Notice how the dedicated vehicle bar is missing the actions
4. Notice how clicking the buttons on the dedicated vehicle bar with your mouse does not do anything
5. Notice how pressing the corresponding keyboard mapping for the buttons does work (i.e. 1, 2, 3, etc)

**Expected Behavior**
The Dedicated Vehicle Bar should show the vehicle actions and they should be usable from the bar

**Actual Behavior**
Bar loads but actions are missing

**ElvUI + S&L Enabled**
Happens when just ElvUI and S&L are loaded exclusively

**Only ElvUI Enabled**
Can't reproduce with just ElvUI since this is a S&L feature

**Additional Information**
You guys are great!

**Error Log**
No errors being logged```

```

**Comment by DarthPredator** [comment]
Fixed, will need current dev build of ElvUI to properly work though
