### ISSUE TITLE
Dragonflight Pre-Patch Location Panel: Hearthstones not working

### ISSUE THREAD

**Issue by Kazuhma** [Shadow-and-Light/shadow-and-light#45]
**Description**
Relocation portion of location panel shows all the correct hearthstones and engineering toys, but they do not work e.g. clicking on the respective entry does nothing.

**Shadow & Light Version**
4.45

**ElvUI Version**
12.95

**Steps to Reproduce**

1. Right click on Location Panel at top of screen
2. Left click on hearthstone or engineering toy line entry

**Expected Behavior**
The respective hearthstone or engineering toy should be invoked

**Actual Behavior**
Nothing happens

**ElvUI + S&L Enabled**

**Only ElvUI Enabled**
Same behaviour

**Additional Information**
n/a

**Error Log**
n/a

**Comment by DarthPredator** [comment]
There was an issue with the option to cast on key up or down.
Should be working just fine with the dev build
