### ISSUE TITLE
Menu "Shadow & Light" button produces error

### ISSUE THREAD

**Issue by cotoga** [Shadow-and-Light/shadow-and-light#52]
**Description**
Since last updated (Elvui 13.01 and S&L 4.47) some UI buttons are producing errors

**Shadow & Light Version**
4.47

**ElvUI Version**
13.01

**Steps to Reproduce**
1. Open game menu (ESC)
2. click button "Shadow & Light"

**Expected Behavior**
Opening Shadow & Light Settings

**Actual Behavior**
Nothing happing and lua error instead

**ElvUI + S&L Enabled**
same

**Only ElvUI Enabled**
only Shadow & Light relvant

**Additional Information**

**Error Log**
```
Message: Interface/AddOns/ElvUI_SLE/core/gameMenu.lua:17: attempt to call method 'ToggleOptionsUI' (a nil value)
Time: Sat Nov 12 15:43:55 2022
Count: 1
Stack: Interface/AddOns/ElvUI_SLE/core/gameMenu.lua:17: attempt to call method 'ToggleOptionsUI' (a nil value)
[string "=[C]"]: in function `ToggleOptionsUI'
[string "@Interface/AddOns/ElvUI_SLE/core/gameMenu.lua"]:17: in function <Interface/AddOns/ElvUI_SLE/core/gameMenu.lua:15>

Locals: 
```
![Wow_3rZ8hZcYoe](https://user-images.githubusercontent.com/11034263/201479574-2f3e0e93-2c07-4428-a784-64726aefaac9.png)

**Comment by cotoga** [comment]
in core/gameMenu.lua

change line17 to:
E:ToggleOptions()

works for me after modifying and reloadUI

**Comment by billgrant** [comment]
Worked for me as well.
