### ISSUE TITLE
Error)

### ISSUE THREAD

**Issue by xzWhiteWolf** [Shadow-and-Light/shadow-and-light#54]
**Description**
Hi! I hover the mouse over the "friends" section. After this error pops up. Sorry, Google translator)

**Shadow & Light Version**
4.50

**ElvUI Version**
13.03

**Steps to Reproduce**

1. Step 1
2. Step 2
3. Step 3
4. Step 4

**Expected Behavior**

**Actual Behavior**

**ElvUI + S&L Enabled**

**Only ElvUI Enabled**

**Additional Information**

**Error Log**
14x :HookScript is not allowed on LibQTip tooltips
[string "@Interface/AddOns/ElvUI/Core/General/Toolkit.lua"]:155: in function `SetTemplate'
[string "@Interface/AddOns/ElvUI_SLE/modules/datatexts/friends.lua"]:578: in function <...rface/AddOns/ElvUI_SLE/modules/datatexts/friends.lua:578>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/ElvUI_SLE/modules/datatexts/friends.lua"]:751: in function `func'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:94: in function <...ce/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua:84
```

```

**Comment by Repooc** [comment]
Already fixed in the dev build
