### ISSUE TITLE
Recent update is creating an invisible minimap button.

### ISSUE THREAD

**Issue by Zithyxx** [Shadow-and-Light/shadow-and-light#58]
**Description**
With the most recent update, I've been encountering a problem between S&L and ProjectAzilroka where having the Square Minimap Buttons enabled will show a blank square. After doing some testing, enabling and disabling addons, it seems that S&L is causing the problem. After going through every S&L option, I can't seem to find a way to disable it. It just seems like S&L is creating an invisible minimap icon and addons like ProjectAzilroka can detect it.

**Shadow & Light Version**
4.51

**ElvUI Version**
13.06

**Steps to Reproduce**
1. Run through default installation of ElvUI
2. Run through default installation of S&L
3. Enable ProjectAzilroka Square Minimap Button
4. Blank square will appear and will only go away once S&L is disabled.

**Expected Behavior**
There shouldn't be a blank minimap button square.

**Actual Behavior**
There is a blank minimap square.

**ElvUI + S&L Enabled**
I cannot reproduce it with only ElvUI and S&L because there's no way to manage minimap icons with only those two addons, so the invisible icon is probably still on the minimap, you just can't see it.

**Only ElvUI Enabled**
Disabling S&L makes it disappear.

**Comment by Repooc** [comment]
pa already has a fixed in the alpha/dev build
