### ISSUE TITLE
S&L LUA error when TomTom is installed. 

### ISSUE THREAD

**Issue by darkdelusions** [Shadow-and-Light/shadow-and-light#59]
When S&L is enabled along side [TomTom](https://www.curseforge.com/wow/addons/tomtom) I receive the following Lua error. Once S&L is disabled and the error goes away. 

`Message: ...ce/AddOns/ElvUI_SLE/modules/unitframes/roleIcons.lua:7: attempt to index field 'unitframes' (a nil value)
Time: Sun Nov 27 20:32:10 2022
Count: 3
Stack: ...ce/AddOns/ElvUI_SLE/modules/unitframes/roleIcons.lua:7: attempt to index field 'unitframes' (a nil value)
[string "@Interface/AddOns/ElvUI_SLE/modules/unitframes/roleIcons.lua"]:7: in function <...ce/AddOns/ElvUI_SLE/modules/unitframes/roleIcons.lua:5>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/oUF/elements/grouproleindicator.lua"]:67: in function `func'
[string "@Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua"]:221: in function `UpdateAllElements'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/Groups/Party.lua"]:213: in function `func'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:830: in function `UpdateChild'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:851: in function `Update'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:802: in function `Update'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1015: in function `CreateAndUpdateHeaderGroup'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1080: in function `LoadUnits'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1684: in function `func'
[string "@Interface/AddOns/ElvUI_Libraries/Core/oUF/factory.lua"]:20: in function <...nterface/AddOns/ElvUI_Libraries/Core/oUF/factory.lua:16>
[string "=(tail call)"]: ?

Locals: self = ElvUF_PartyGroup1UnitButton6 {
 ReadyCheckIndicator = Texture {
 }
 BORDER = 1
 UNIT_MAXPOWER = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua:1082
 unitEvents = <table> {
 }
 PhaseIndicator = Texture {
 }
 AuraHighlightBackdrop = false
 USE_INSET_POWERBAR = false
 UNIT_MAXHEALTH = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua:1082
 __customargs = <table> {
 }
 AuraHighlight = Texture {
 }
 RaisedElementParent = Frame {
 }
 ClassBar = "AlternativePower"
 RAID_TARGET_UPDATE = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/elements/raidtargetindicator.lua:62
 Debuffs = ElvUF_PartyGroup1UnitButton6Debuffs {
 }
 UNIT_HEAL_PREDICTION = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua:1082
 unit = "party1"
 db = <table> {
 }
 unitframeType = "party"
 POWERBAR_HEIGHT = 13
 hasChildren = true
 CAN_HAVE_CLASSBAR = true
 Buffs = ElvUF_PartyGroup1UnitButton6Buffs {
 }
 MouseGlow = Frame {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua:73
 INCOMING_RESURRECT_CHANGED = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/elements/resurrectindicator.lua:60
 UNIT_CLASSIFICATION_CHANGED = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/elements/pvpclassificationindicator.lua:83
 UNIT_PET = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua:242
 GroupRoleIndicator = Texture {
 }
 Cutaway = <table> {
 }
 CLASSBAR_SHOWN = false
 Castbar = ElvUF_PartyGroup1UnitButton6_CastBar {
 }
 UNIT_HEAL_ABSORB_AMOUNT_CHANGED = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua:1082
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/elements/threatindicator.lua:91
 AuraHighlightFilter = true
 POWERBAR_DETACHED = false
 USE_MINI_CLASSBAR = false
 Portrait = PlayerModel {
 }
 UNIT_ABSORB_AMOUNT_CHANGED = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/ouf.lua:1082
 RaidTargetIndicator = Texture {
 }
 SPACING = 0
 UNIT_HEIGHT = 74
 USE_POWERBAR_OFFSET = false
 INCOMING_SUMMON_CHANGED = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/elements/summonindicator.lua:74
 PARTY_MEMBER_DISABLE = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/oUF/elements/health.lua:143
 LeaderIndicator = Texture {
 }
 RaidDebuffs = Frame {
 }
 UNIT_POWER_BAR_HIDE = <table> {
 }
 UNIT`

**Comment by Repooc** [comment]
well s&l and tomtom do not have anything in common, sounds like it just happens to display the error for whatever reason... i dont know how you update ur addons, mainly s&l, but if you manually update, make sure you are deleting ElvUI_SLE folder and replacing with a new one.  only reason why that would show nil is something/someone is setting that part of the table to nil which isnt suppose to happen
i would start with `/slerror on` and see if u get the error and if so, do `/estatus` and show a picture of the error and window that opens with the estatus command.

**Comment by darkdelusions** [comment]
I generally use the Takui Client to update S&L and Elvui. 

So I went ahead and performed an /slerror on and did not receive the error and upon turning it off the error no longer pops up.

 I apologize I didn't realize /slerror was a command

**Comment by Repooc** [comment]
> rror and upon tur

all that does is disable all other addons but elvui and s&l

**Comment by darkdelusions** [comment]
I figured that was all it did, however I logged out of the game several times, reloaded the ui, and logged into other toons and I am unable to recreate the error again.  

Prior to that the error was happening consistently
