### ISSUE TITLE
After cutscene viewport stops working

### ISSUE THREAD

**Issue by sergeysh93** [Shadow-and-Light/shadow-and-light#6]
**Description**

**Shadow & Light Version**

4.26

**ElvUI Version**

12.35

**Steps to Reproduce**

1. Sylvana's encounter phase 1 cutscene

**Expected Behavior**

After cutscene viewport should apply settings again

**Actual Behavior**

Viewport stops working

**ElvUI + S&L Enabled**

**Only ElvUI Enabled**

**Additional Information**

**Error Log**

```

```

**Comment by mirr0din** [comment]
Any updates to this issue?

**Comment by Repooc** [comment]
> Any updates to this issue?

Can you try the lastest alpha build

**Comment by mirr0din** [comment]
Tried it with Build 4.29-11-g753add0 and had no issues anymore. Thanks for the advice and keep up the good work!

**Comment by Repooc** [comment]
ty vm
