### ISSUE TITLE
Dragon riding talent tree missing 

### ISSUE THREAD

**Issue by ethanvanorton** [Shadow-and-Light/shadow-and-light#61]
**Description**
after installing and using Darth’s config, the mini map button for the dragon riding talent tree is missing. I don’t see an option to show it in the map settings.

if I import the previous profile, it comes back.

**Shadow & Light Version**
4.54

**ElvUI Version**
13.07

**Steps to Reproduce**
1. Use Darth’s config from install wizard
2. Button no longer showing on mini map

**Expected Behavior**
Button for dragon riding talent tree shows on mini map or elsewhere in UI. 

**Actual Behavior**
Button above is missing. Not aware of a keyboard shortcut or accessing dragon riding talent tree from micro bar.

**ElvUI + S&L Enabled**
Only happens with Darth’s config

 n/a no lua error

**Additional Information**

**Error Log**

```

```

**Comment by Repooc** [comment]
U have elvuis garrison option set to hide which is why you don't it when using his profile

**Comment by ethanvanorton** [comment]
Thanks worked, thank you!
