### ISSUE TITLE
Reputation chatfilter not working for dragonflight renown

### ISSUE THREAD

**Issue by eleanoryeung** [Shadow-and-Light/shadow-and-light#62]
**Description**
Enabling reputation chatfilter under "databars" will disable all reputation notices, but the new one is not shown.

**Shadow & Light Version**
4.54

**ElvUI Version**
13.09

**Steps to Reproduce**
1. enable chatfilter
2. do some quests

**Expected Behavior**
Show edited version of notice

**Actual Behavior**
Nothing shows

**Comment by Repooc** [comment]
already been fixed in the dev build... looking to do a release at some point tonight... before i go to bed
