### ISSUE TITLE
LUA-Error on Reputation Gain.

### ISSUE THREAD

**Issue by Marvin10193** [Shadow-and-Light/shadow-and-light#63]
**Description**
Reputation gain is not showing in the chat. Additionally, any repuration gain in Dragonflight throws a LUA-Error.
This only happens with the Chat Filters enabled under SL -> Databars -> Reputation -> Chat Filters.

**Shadow & Light Version**
4.55

**ElvUI Version**
13.09

**Steps to Reproduce**
1. Have the Chat filters setting in SL -> Databars ->Reputation Enabled
2. Gain any Reputation, e.g., from a quest etc.

**Expected Behavior**
Should show the reputation gain in the chat with a symbol instead of the normal text.

**Actual Behavior**
No text is shown at all in the chat and a LUA-Error is thrown

**Error Log**
```
2x ElvUI_SLE/modules/databars/rep.lua:172: bad argument #1 to 'format' (string expected, got nil)
[string "=[C]"]: ?
[string "@ElvUI_SLE/modules/databars/rep.lua"]:172: in function `filterFunc'
[string "@ElvUI/Core/Modules/Chat/Chat.lua"]:1806: in function `ChatFrame_MessageEventHandler'
[string "@ElvUI/Core/Modules/Chat/Chat.lua"]:2253: in function `ChatFrame_OnEvent'
[string "@ElvUI/Core/Modules/Chat/Chat.lua"]:2257: in function `FloatingChatFrame_OnEvent'
[string "@ElvUI/Core/Modules/Chat/Chat.lua"]:2262: in function <ElvUI/Core/Modules/Chat/Chat.lua:2261>

Locals:
(*temporary) = nil
(*temporary) = 12
(*temporary) = "Dragonscale Expedition"
(*temporary) = "275"
(*temporary) = "string expected, got nil"
```

**Comment by Repooc** [comment]
Already been fixed in the development branch
