### ISSUE TITLE
Enhanced Vehicle Bar does not work after ElvUI is updated to 12.38

### ISSUE THREAD

**Issue by soeron** [Shadow-and-Light/shadow-and-light#7]
**Description**
The enhanced vehicle bar does not show when override bar should be shown.

**Shadow & Light Version**
4.26

**ElvUI Version**
12.38

**Steps to Reproduce**
Go in Korthia and ride the Assault Supply Carriage

**Expected Behavior**
The override bar shown as configured in the Action Bar menu

**Actual Behavior**
No bar is show and the main bar from ElvUI is hidden

**ElvUI + S&L Enabled**
Yes

**Only ElvUI Enabled**
NA

```

```

**Comment by juntereiner** [comment]
I had to use the 4.24 version to work with latest version of elvui.

**Comment by juntereiner** [comment]
Latest version fixed this issue :)

**Comment by Repooc** [comment]
sweet i forgot about the ticket haha
