### ISSUE TITLE
Request for images of the plugin in use.

### ISSUE THREAD

**Issue by RyanScarbrough** [Shadow-and-Light/shadow-and-light#71]
On the CurseForge website, your plugin has no images of it uploaded. Given that this is a UI plugin, it would be useful for people to see what it looks like, rather than have to install to see what it is.

**Comment by Repooc** [comment]
s&l is more about the modules it has to offer, not darth's profile that is included in the installer, as that is supplied mainly for Darth to setup his toons quickly and not need to keep a backup of his wtf folder (same goes for me if i ever add my profile back)
