### ISSUE TITLE
Enhanced Shadows Class bar evoker keep disappearing

### ISSUE THREAD

**Issue by ATROZITY** [Shadow-and-Light/shadow-and-light#74]
**Description**
The enhanced shadows for the detatched class bar keeps disappearing after relog.
After a relog or reload of the UI you need to apply the enhanced shadows for te players class bar every time on the Evoker preservation class

**Shadow & Light Version**
Version 4.57

**ElvUI Version**
Version 13.15

**Steps to Reproduce**

*5 Essence classbar*
1. Have a detatched from frame class bar
2. Do not have the talent selected for the evoker that gives you 6 essence
3. Enable Enhanced Shadows -> Unitframe -> Player -> Classbar
4. Log out of character
5. Log in to character
6. Enchanced shadows are gone
7. Reload UI
8. Enhanced shadows still gone

You need to enable them manually again
----------------------------------
*6 Essence classbar*
1. Have a detatched from frame class bar
2. Have the talent Power Nexus selected for the evoker that gives you 6 essence
3. Enable Enhanced Shadows -> Unitframe -> Player -> Classbar
4. Log out of character
5. Log in to character
6. Enchanced shadows are stil visible
10. Reload UI
11. Enhanced shadows still gone

You need to enable them manually again

**Expected Behavior**
The enhanced shadows on the evoker should stay visible/enabled regardless of essence amount and relog/reload UI.

**Actual Behavior**
Enhanced shadows on the evoker keeps disappearing after each relog or reload of UI on the evoker.
So that you need to manualy enable them each time you enter the character or you reload the UI.

**ElvUI + S&L Enabled**
All addons disabled except Elvui & S&L this keeps happening.
Only happens as far as i tested on the Evoker class.
If you log out and log in from the character the shadows disappear if you have 5 essence. enabling them again makes them visible again but after a reload UI they disappear again.
if you have 6 essence the shadows stays but after a reload of the UI they disappear.

**Only ElvUI Enabled**
Cannot reproduce because this is an Shadow and light functionality

**Additional Information**
Tested this on other class like rougue and it work as intended.
the enhanced shadows only disappear from the class bar of the evoker the other bars and frames stay enabled as intended en configured.

**Error Log**
No error log

![image](https://user-images.githubusercontent.com/121467325/209596918-265e6e19-6457-4b5d-bb07-efb113e338fd.png)

```

```

**Comment by Repooc** [comment]
this has already been fixed in commit aedc3ce84dff4d7a3f58a7294155284ca16aedf1 which a new version has not been released yet with this fix
