### ISSUE TITLE
Guardian spirit wont work

### ISSUE THREAD

**Issue by Paleogod** [Shadow-and-Light/shadow-and-light#75]
**Description**
The spell Guardian spirit will not work

**Shadow & Light Version**
4.57

**ElvUI Version**
13.17

**Steps to Reproduce**

1. have ELVui and or Shadow and light
2. priest holy spec with Guardian spirt  talent
3. use Guardian spirt  spell on self or others
4. disable and try again now it works
5. reenable and now it wont work again

**Expected Behavior**
the spell should work

**Actual Behavior**
said no target

**ElvUI + S&L Enabled**
 yes it still happens
 yes it still happens
  yes it still happens

**Only ElvUI Enabled**
 yes it still happens
 yes it still happens
 yes it still happens

**Additional Information**
it works when i disable ELVui and Shadow and light, but stops again when i reactivate it.

**Error Log**
none that i see other then no target

```

```
![WoWScrnShot_010423_201957](https://user-images.githubusercontent.com/121994289/210694630-88c1528a-d29d-41f4-9cd3-79470314a85b.jpg)

**Comment by Repooc** [comment]
shadow & light doesnt alter how spells are casted or messes with the actionbars in a way a spell wont cast, esp just the one spell. sounds like an issue with self cast option (not s&l related again)
