### ISSUE TITLE
bug with paper character screen

### ISSUE THREAD

**Issue by grilor** [Shadow-and-Light/shadow-and-light#79]
when the character screen is open all my stats on the side blink on and off and when I move the box some of it stays where is was originally.

**Comment by Repooc** [comment]
`/slerror on` then retest and show `/estatus` if u can make a video of this instead, that would be better

**Comment by Toasticon** [comment]
Essentially the stat info panel behaves like a load-on-demand module with a slight delay since 10.0.5 or so. If you reopen it it'll load like intended and stay in memory until you kill the wow client.
