### ISSUE TITLE
"Dedicated Vehicle Bar" keybind text for the last button (button 7) is wrong

### ISSUE THREAD

**Issue by Okidokidude** [Shadow-and-Light/shadow-and-light#80]
**Description**
"Dedicated Vehicle Bar" keybind text for the last button (button 7) is wrong, it shows the keybind text for actionbar1 button12 

**Shadow & Light Version**
4.60

**ElvUI Version**
13.26

**Steps to Reproduce**
1. Enable SL vehicle bar
2. Try drag something on to the last vehicle button (7) you can test with dragon riding.
3. Nothing will happen when you press that keybind,
4. Instead press your keybind for action bar 1 button 7 instead and it works, even though the vehicle bar tells you it's the keybind for button 12.

**Expected Behavior**
Button 7 should trigger on the keybind that shows on vehicle bar button 7.
OR vehicle bar button7 should show the keybind text for action bar 1 button 7, not 12.

**Actual Behavior**
Vehicle bar button 7 show's keybind text for button 12, but should show for button 7.

**ElvUI + S&L Enabled**
Always is like this,

**Only ElvUI Enabled**
Can't test this, since SL is the only way to get ther vehicle bar.

**Additional Information**
Not sure what to add here, just change keybind text i guess on vehicle button 7 to actionbar 1 button 7 instead of 12?
[https://prnt.sc/3NVpycRfx_5G](url)
[https://prnt.sc/Kf-8DkjPW5v1](url)

**Error Log**

```

```

**Comment by Okidokidude** [comment]
The pic links didn't work, so dragging em here:
![1](https://user-images.githubusercontent.com/125795231/219941768-036d2070-d9ad-4809-976e-1fdb71839979.png)
![2](https://user-images.githubusercontent.com/125795231/219941771-1f2e0fce-0d9b-491c-b20e-241dc196f5c9.png)

**Comment by E-Tsx** [comment]
no, the last button in vehicle bar is for exit vehicle, so bar 1 button 12

**Comment by Okidokidude** [comment]
Well it doesn't do that either.
![Screenshot_7](https://user-images.githubusercontent.com/125795231/219971985-0de88cd7-94bf-496a-9a9e-709a647ba562.png)

**Comment by Repooc** [comment]
Fix had been pushed and will be in the next release
