### ISSUE TITLE
Запомненное положение сбрасывается после боя

### ISSUE THREAD

**Issue by Hollicsh** [Shadow-and-Light/shadow-and-light#81]
**Description**
Запомненное положение сбрасывается после боя.

**Shadow & Light Version**
4.60

**ElvUI Version**
13.26

P.S. Special for Darth.

**Comment by Repooc** [comment]
i been thinking about removing said option bc of all the headaches and shit from various blizzard frames and there are addons that are doing it better like projectazilroka and [demodal](https://www.curseforge.com/wow/addons/demodal)

**Comment by Hollicsh** [comment]
Нюансик: Когда карта была открыта во время боя, то после окончания боя она не возвращается на место.

P.S. Special for Darth.
