### ISSUE TITLE
Unitframe -> General -> Texture options not working

### ISSUE THREAD

**Issue by Okidokidude** [Shadow-and-Light/shadow-and-light#83]
**Description**
Changing the texture for Castbar and Classbar does nothing, the default ElvUI texture still remains.
Worked fine some versions ago, reload does not help.
The new selected texture sticks in the options but no change in the actual texture display.

**Shadow & Light Version**
4.60

**ElvUI Version**
13.27

**Steps to Reproduce**
1. Change texture.
2. Watch that the textures are not actually changed.
3. Try to reload ui.
4. Still no textures changed.

**Expected Behavior**
Texture should change like it used to.

**Actual Behavior**
The default ElvUI texture is showing,

**ElvUI + S&L Enabled**
Tried this, still the same.

**Only ElvUI Enabled**
Can't test since it requires S&L

**Additional Information**

**Error Log**
No errors.
```

```

**Comment by Repooc** [comment]
you will need to do `/slerror on` and test again as i cant seem to reproduce ur issue with just ElvUI and S&L installed

https://user-images.githubusercontent.com/1479745/222974238-7ab5d4aa-2e68-4b7f-af13-619976daa320.mp4

**Comment by Okidokidude** [comment]
I already did /slerror on
Not sure what else i can do.

**Comment by Okidokidude** [comment]
![Screenshot_14](https://user-images.githubusercontent.com/125795231/222974464-114ebfe3-3f48-4a07-8f33-35322ae2fc7e.png)

**Comment by Okidokidude** [comment]
You can see the castbar in motion there.

**Comment by Repooc** [comment]
when u do a picture showing ur issue, make sure to show `/estatus` as well bc it will looks like u have other addons enabled in that picture to me

**Comment by Okidokidude** [comment]
I do have more addons enabled, when i reported the bug i did all the testing on my evoker with /slerror ON.
This is a screenshot i took on my Shaman just now.
Will /estatus with slerror on after raid.

**Comment by Repooc** [comment]
also, if u are actively messing around. this could be a bit faster if u were on our discord server... as i played with some of the cast bar options in elvui config -> unitframes -> colors -> cast bar... which some can make it look like its not working bc how elvui changes the texture we replace to a different frame level

**Comment by Repooc** [comment]
oh you are in a raid.  yeah depending on how long u will be, i prob will be around still

**Comment by Okidokidude** [comment]
Ok, you are a genious, that fixed it!
Classbar --> Parent: UIPARENT
Colors --> Castbar --> untick "transparent"

Thanks you, and sorry for wasting your time!

**Comment by Repooc** [comment]
yeah i figured it was something stupid like that lol
