### ISSUE TITLE
Armury Mode is broken

### ISSUE THREAD

**Issue by Sansaculotte** [Shadow-and-Light/shadow-and-light#86]
Hi, armury mod in my S&L doesn't work anymore, I had "attributes" checked and my characters stats aren't displayed anymore, I had to disable this option to see my stats again.

**Comment by Sansaculotte** [comment]
I saw there was an update with a fix, but still doesn't work for me
![Capture d’écran 2023-03-30 065642](https://user-images.githubusercontent.com/125482799/228733718-9a6b3441-b3c1-48e3-8dbb-0e923a6b82fa.jpg)

**Comment by Repooc** [comment]
Can you show `/estatus` and any errors?

**Comment by Sansaculotte** [comment]
I don't have errors, maybe tell me how can I found it ?
![Capture d’écran 2023-03-30 071244](https://user-images.githubusercontent.com/125482799/228735973-ea3ea744-bde8-496a-a422-8e62e5112db1.jpg)

**Comment by Sansaculotte** [comment]
Message: Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:594: Usage: BreakUpLargeNumbers(number[, natural])
Time: Thu Mar 30 07:18:13 2023
Count: 1
Stack: Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:594: Usage: BreakUpLargeNumbers(number[, natural])
[string "@Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua"]:151: in function <...dOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:149>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua"]:594: in function <Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:582>
[string "@Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua"]:920: in function `updateFunc'
[string "@Interface/FrameXML/PaperDollFrame.lua"]:1950: in function <Interface/FrameXML/PaperDollFrame.lua:1888>
[string "=[C]"]: ?
[string "=[C]"]: in function `PaperDollFrame_UpdateStats'
[string "@Interface/FrameXML/PaperDollFrame.lua"]:1443: in function <Interface/FrameXML/PaperDollFrame.lua:1439>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2897: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2740: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2605: in function <Interface/FrameXML/UIParent.lua:2601>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3207: in function `ShowUIPanel'
[string "@Interface/FrameXML/CharacterFrame.lua"]:21: in function `ToggleCharacter'
[string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>

Locals: private = <table> {
 ThrowError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:50
 DoesErrorExist = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:92
 ClearOldErrors = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:112
 SanitizeLine = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:88
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:121
 IncrementErrorCount = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:82
 NewError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:54
 IsRCLootCouncilError = <function> defined @Interface/AddOns/RCLootCouncil/Classes/Services/ErrorHandler.lua:99
}
orig_errorhandler = <function> defined @Interface/SharedXML/SharedBasicControls.lua:360

**Comment by Sansaculotte** [comment]
Message: Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:594: Usage: BreakUpLargeNumbers(number[, natural])
Time: Thu Mar 30 07:21:30 2023
Count: 4
Stack: Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:594: Usage: BreakUpLargeNumbers(number[, natural])
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua"]:594: in function <Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:582>
[string "@Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua"]:920: in function `updateFunc'
[string "@Interface/FrameXML/PaperDollFrame.lua"]:1950: in function <Interface/FrameXML/PaperDollFrame.lua:1888>
[string "=[C]"]: ?
[string "=[C]"]: in function `PaperDollFrame_UpdateStats'
[string "@Interface/FrameXML/PaperDollFrame.lua"]:381: in function <Interface/FrameXML/PaperDollFrame.lua:379>

Locals:

**Comment by Repooc** [comment]
yeah i derped earlier and have a fix incoming soon

**Comment by Sansaculotte** [comment]
It works perfectly now :) thx for your work !
