### ISSUE TITLE
New version on curse being treated as Trojan

### ISSUE THREAD

**Issue by Genhard** [Shadow-and-Light/shadow-and-light#9]
**Description**

Tried updating Shadow & Light on curse and my windows detected as trojan

**Shadow & Light Version**

4.29

**ElvUI Version**

12.43

**Steps to Reproduce**

1. Step 1 Try to update
2. Step 2 Fail
3. Step 3
4. Step 4

**Expected Behavior**

Addons update

**Actual Behavior**

Addons doesn't update
**ElvUI + S&L Enabled**

**Only ElvUI Enabled**

**Additional Information**

Windows says "Trojan:Script/Wacatac.B!ml" 
Located "C:\Users\xxxx\AppData\Local\Temp\CF\OT6ItprEkUGylu5kdyrh6A\10.zip"
Windows 10 pro version 21H1

**Error Log**

```
```

**Comment by Repooc** [comment]
I dont know why yours would flag it but not mine, i even downloaded it and had it scanned with windows defender as well as virustotal.com so 🤷 
[https://www.virustotal.com/gui/file/a5b87394fff913d06ee8480577b9f6474a2f5b7e4fff5e8bec3b68d64dfa1bf3/detection](url)
