### ISSUE TITLE
Random "Attack" button at character panel after update

### ISSUE THREAD

**Issue by pesrou** [Shadow-and-Light/shadow-and-light#98]
**Description**
Random "Attack" button at character panel after update with all skins disabled in Elvui. I do know it shows up if I have the skin enabled on Elvui, but I do not have any skin on the screenshot.

**Shadow & Light Version**

**ElvUI Version**

13.52

**Steps to Reproduce**

1. Step 1: Open Character Panel
2. Step 2: Done

**Expected Behavior**
Not a random "attack" button showing up

**Actual Behavior**
A random "attack" button showing up

**ElvUI + S&L Enabled**

Yes, basically turning Shadow & Light on in addon panel.
**Only ElvUI Enabled**

Yes, basically turning Shadow & Light on in addon panel.

**Additional Information**

Pretty simple visual bug

**Error Log**

No errors, screenshot showing the bug in question below:

![Screenshot 2023-11-22 000157](https://github.com/Shadow-and-Light/shadow-and-light/assets/93722498/c9a1a555-f28b-4381-be21-903d1ba73835)

**Comment by pesrou** [comment]
Just to be safe: this error only appears when Shadow & Light is enabled.

**Comment by Repooc** [comment]
turn off the Attributes option in the Armory Mode

**Comment by Repooc** [comment]
should also double check if u have ur issues after doing `/slerror on`

**Comment by pesrou** [comment]
Armory mode is Off since I've disabled all skins. Here is the Lua Error:

/Message: Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:196: attempt to index field 'backdrop' (a nil value)
Time: Wed Nov 22 02:11:40 2023
Count: 1
Stack: Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:196: attempt to index field 'backdrop' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua"]:196: in function <Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:168>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `PaperDollFrame_UpdateStats'
[string "@Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua"]:365: in function `ToggleArmory'
[string "@Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua"]:950: in function `LoadAndSetup'
[string "@Interface/AddOns/ElvUI_SLE/modules/armory/armory.lua"]:535: in function <Interface/AddOns/ElvUI_SLE/modules/armory/armory.lua:527>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_SLE/core/toolkit.lua"]:276: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI_SLE/core/core.lua"]:117: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua"]:309: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:305>
[string "=[C]"]: in function `Initialize'
...
[string "@Interface/FrameXML/UIParent.lua"]:542: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:747: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by Repooc** [comment]
> Armory mode is Off since I've disabled all skins. Here is the Lua Error:
> 
> /Message: Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:196: attempt to index field 'backdrop' (a nil value) Time: Wed Nov 22 02:11:40 2023 Count: 1 Stack: Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:196: attempt to index field 'backdrop' (a nil value) [string "=[C]"]: ? [string "@Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua"]:196: in function <Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua:168> [string "=(tail call)"]: ? [string "=[C]"]: in function `PaperDollFrame_UpdateStats' [string "@Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua"]:365: in function `ToggleArmory' [string "@Interface/AddOns/ElvUI_SLE/modules/armory/stats.lua"]:950: in function `LoadAndSetup' [string "@Interface/AddOns/ElvUI_SLE/modules/armory/armory.lua"]:535: in function <Interface/AddOns/ElvUI_SLE/modules/armory/armory.lua:527> [string "=[C]"]: ? [string "@Interface/AddOns/ElvUI_SLE/core/toolkit.lua"]:276: in function `InitializeModules' [string "@Interface/AddOns/ElvUI_SLE/core/core.lua"]:117: in function `?' [string "@Interface/AddOns/ElvUI_Libraries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua"]:309: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:305> [string "=[C]"]: in function `Initialize' ... [string "@Interface/FrameXML/UIParent.lua"]:542: in function `UIParentLoadAddOn' [string "@Interface/FrameXML/UIParent.lua"]:747: in function `MajorFactions_LoadUI' [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList' [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList' [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay' [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154> [string "=[C]"]: in function `CreateFrame' [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay' [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay' [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>
> 
> Locals: (*temporary) = defined =[C]:-1

Show the settings of the armory mode section, as the section I was referring to is Attributes (not tech armory but in the same section) as the only way to get to that part of the code that it errored on is if you have the Attributes option enabled (even though you have the skin disabled, they have nothing to do with each other really) as you sound like you dont want our stats section enabled and use blizzards default.

**Comment by Repooc** [comment]
i put a check in for the backdrop error but like I said before, go to the Armory section and disable the stats part (aka Attributes) as it sounds like you don't want that enabled.

**Comment by pesrou** [comment]
I've run installation again, disabled armory again, the addon shows the armory is disabled to "avoid the graphic to be broken as heck" (which funny enough, it is broken)
![Screenshot 2023-11-22 181714](https://github.com/Shadow-and-Light/shadow-and-light/assets/93722498/0f9372d2-04a3-427d-a41f-a8345031d0b5)

**Comment by Repooc** [comment]
> I've run installation again, disabled armory again, the addon shows the armory is disabled to "avoid the graphic to be broken as heck" (which funny enough, it is broken) ![Screenshot 2023-11-22 181714](https://user-images.githubusercontent.com/93722498/285044101-0f9372d2-04a3-427d-a41f-a8345031d0b5.jpg)

hhmmm prob not working as he expected,
enable skin, go to the armory mode and uncheck atrributes, disable skin
try that

**Comment by pesrou** [comment]
Doing this removes the "Attack" visual bug, although I'm pretty sure I always used the Armory without skins, it's the only reason why I have this addon in the first place

**Comment by pesrou** [comment]
Just noticed as well that when this visual bug is present, I cannot scroll through my stats as it used to as well

**Comment by Repooc** [comment]
Well the armory being disabled with the skins has been a thing for at the min, 2 years or so, like back in 2019.


> Just noticed as well that when this visual bug is present, I cannot scroll through my stats as it used to

assuming you mean skin disabled and attributes enabled which isnt supported, so expect bugs.  i will have to put a check in so attributes do not try to run with skin disabled
if i have extra time, i may try to make the stats work without elvui skin

**Comment by Repooc** [comment]
btw we have a discord that is easier for back and forth talking

**Comment by pesrou** [comment]
Oh that explains it then, I've been "away" from most addons since Shadowlands 
Right, let me hit you up on discord

**Comment by Repooc** [comment]
https://repooc.dev/sldiscord (no friend requests)

**Comment by Repooc** [comment]
should be fixed in version
